### ISSUE TITLE
https://dotnet.microsoft.com/download/dotnet-framework

### ISSUE THREAD

**Issue by MatthK** [immense/Remotely#391]
First of all, thank you very much for this awesome product. I just found it, and it is really cool. Unfortunately I came across a little problem.

**Describe the bug**
I am trying to install the Resident Agent on an old Windows 7 machine (yes I know, it's outdated). I can connect using the instant support client (but then I have to acknowledge the connection). When I try to install the agent, I get the following error message:

```
2021-11-12 14:26:33.698	[Error]	The request was aborted: Could not create SSL/TLS secure channel.	   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Remotely.Agent.Installer.Win.Services.InstallerService.<DownloadRemotelyAgent>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Remotely.Agent.Installer.Win.Services.InstallerService.<Install>d__13.MoveNext()	System

```
The server runs on Docker, and there is an nginx reverse proxy in front with a Let's Encrypt SSL cert. I was thinking that the Window 7 machine doesn't have the new root cert, so I added manually to the trusted root certs on the client. I also installed .net 4.8 runtime (just in case), but the problem persists. I can login to the website, the connection is shown as secure, but the agent won't install.

**Remotely Version**
Server (can be found on about page):  Version: 2021.08.17.1435
Agent (can be found in device card):  Can't install

**Expected Behavior**
Be able to install the agent

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Window 7 Home, Service Pack 1

**Comment by NitroHype** [comment]
I'm having the same issue with Windows 10 or Windows server 2012, 2016

**Comment by MazixM** [comment]
I had the same bug, and I modified agent installer source code, to be able to install it from local path. Then I sent exe with additional .zip file - work fine. I know is not the solution, but it can help partly, if you need to do it fast.

**Comment by STillSB** [comment]
same issue in windows7
