### ISSUE TITLE
Remote doesn't work on newly installed Ubuntu Machines

### ISSUE THREAD

**Issue by MrMEEE** [immense/Remotely#428]
**Describe the bug**
New installations of Ubuntu 20.04, 21.04 and 19.04 fails to work with remote access

**To Reproduce**
1. Install Ubuntu
2. Install the agent
3. Scroll down to'
4. Get error:
root@mj-HVM-domU:/usr/local/bin/Remotely/Desktop# 
root@mj-HVM-domU:/usr/local/bin/Remotely/Desktop# Dec 29 16:49:41 mj-HVM-domU Remotely_Agent[21909]: Attempting to launch screen caster with username mj, xauthority /home/mj/.Xauthority, display 192.168.60.61, and args -u mj /usr/local/bin/Remotely/Desktop/Remotely_Desktop -mode Unattended -requester "a14534f1-b4e2-4704-841b-cead033e73c6" -serviceid "XXXXXXXXXXXXXXXXXXXXXXX" -deviceid XXXXXXXXXXXXXXXXXXXXX -host "https://remote.mrmeee.dk" -orgid "XXXXXXXXXXXXXXXXXXXXXXXX".
Dec 29 16:49:41 mj-HVM-domU sudo[21927]:     root : PWD=/usr/local/bin/Remotely ; USER=mj ; COMMAND=/usr/local/bin/Remotely/Desktop/Remotely_Desktop -mode Unattended -requester a14534f1-b4e2-4704-841b-cead033e73c6 -serviceid XXXXXXXXXXXXXXXXXXXX -deviceid XXXXXXXXXXXXXXXXXXXXXX -host https://remote.mrmeee.dk -orgid XXXXXXXXXXXXXXXXXXXXXXX
Dec 29 16:49:41 mj-HVM-domU sudo[21927]: pam_unix(sudo:session): session opened for user mj by (uid=0)
Dec 29 16:49:41 mj-HVM-domU kernel: Remotely_Deskto[21928]: segfault at e0 ip 00007f0dff85eda4 sp 00007fff1dd68db8 error 4 in libX11.so.6.4.0[7f0dff84e000+8c000]
Dec 29 16:49:41 mj-HVM-domU kernel: Code: 07 48 03 b7 e8 00 00 00 48 8b 46 10 c3 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 8b 87 e0 00 00 00 c3 0f 1f 44 00 00 f3 0f 1e fa <48> 63 87 e0 00 00 00 48 c1 e0 07 48 03 87 e8 00 00 00 48 8b 40 10
Dec 29 16:49:41 mj-HVM-domU sudo[21927]: pam_unix(sudo:session): session closed for user mj

I have a Ubuntu 21.10 which has been running for a year, and there it works fine, so I expect it to be some kind of dependency??

If I compile the Desktop part by myself, and put it in.. I get this error instead..:

Dec 29 16:54:51 mj-HVM-domU sudo[21976]:     root : PWD=/usr/local/bin/Remotely ; USER=mj ; COMMAND=/usr/local/bin/Remotely/Desktop/Remotely_Desktop -mode Unattended -requester a14534f1-b4e2-4704-841b-cead033e73c6 -serviceid XXXXXXXXXXXXXXXx -deviceid XXXXXXXXXXXXXXXXXXX -host https://remote.mrmeee.dk -orgid XXXXXXXXXXXX
Dec 29 16:54:51 mj-HVM-domU sudo[21976]: pam_unix(sudo:session): session opened for user mj by (uid=0)
Dec 29 16:54:51 mj-HVM-domU Remotely_Agent[21977]: XOpenDisplay failed
Dec 29 16:54:51 mj-HVM-domU Remotely_Agent[21977]: XOpenDisplay failed
Dec 29 16:54:51 mj-HVM-domU Remotely_Agent[21977]: Unhandled exception. System.Exception: XOpenDisplay failed
Dec 29 16:54:51 mj-HVM-domU Remotely_Agent[21977]:    at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options) in /_/src/Avalonia.X11/X11Platform.cs:line 57
Dec 29 16:54:51 mj-HVM-domU Remotely_Agent[21977]:    at Avalonia.AvaloniaX11PlatformExtensions.<>c__0`1.<UseX11>b__0_0() in /_/src/Avalonia.X11/X11Platform.cs:line 266
Dec 29 16:54:51 mj-HVM-domU Remotely_Agent[21977]:    at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 303
Dec 29 16:54:51 mj-HVM-domU Remotely_Agent[21977]:    at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 157
Dec 29 16:54:51 mj-HVM-domU Remotely_Agent[21977]:    at Remotely.Desktop.XPlat.Program.Main(String[] args) in /home/mj/Hentet/remotely-agent/Desktop.XPlat/Program.cs:line 33
Dec 29 16:54:51 mj-HVM-domU sudo[21976]: pam_unix(sudo:session): session closed for user mj

**Remotely Version**
Server 2021.08.26.1335:
Agent 2021.08.26.1335:

**Expected Behavior**
Remote connection to open

**Additional Context**
Hope you can help..

**Comment by MrMEEE** [comment]
On my 21.10, it actually also throws the segfault... så it's before that, that the new machines doesn't work...

**Comment by MrMEEE** [comment]
got the failing to output more debug:

Processing Args: -mode, Unattended, -requester, 4345532f-0e9e-409b-a760-7bd6a4ffd826, -serviceid, XPGCzgervkYGacbYwxcCgg, -deviceid, eade4d44-33ec-44de-b0c0-3a8bf9322d26, -host, https://remote.mrmeee.dk, -orgid, 2ee81029-cc7d-46bb-99e9-f29faa73b9a7
Found monitor: 1024,768,0, 0
Setting new screen bounds: 1024,768,0, 0
Starting screen cast.  Requester: m@rtinjuhl.dk. Viewer ID: vLmRoJG__ZPSdD-bL8p1_w.  App Mode: Unattended
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Remotely.Desktop.XPlat.Services.ScreenCapturerLinux.GetX11Capture()
   at Remotely.Desktop.XPlat.Services.ScreenCapturerLinux.GetNextFrame()
   at Remotely.Desktop.Core.Services.ScreenCaster+<CastScreen>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Remotely.Desktop.Core.Services.ScreenCaster+<CastScreen>d__6, Remotely_Desktop.Core, Version=2021.8.26.1335, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Remotely.Desktop.Core.Services.ScreenCaster+<CastScreen>d__6, Remotely_Desktop.Core, Version=2021.8.26.1335, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Remotely.Desktop.Core.Services.ScreenCaster+<CastScreen>d__6, Remotely_Desktop.Core, Version=2021.8.26.1335, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Remotely.Desktop.Core.Services.Viewer+<SendCursorChange>d__75.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Remotely.Desktop.Core.Services.Viewer+<SendCursorChange>d__75, Remotely_Desktop.Core, Version=2021.8.26.1335, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Remotely.Desktop.Core.Services.Viewer+<SendCursorChange>d__75, Remotely_Desktop.Core, Version=2021.8.26.1335, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Remotely.Desktop.Core.Services.Viewer+<SendCursorChange>d__75, Remotely_Desktop.Core, Version=2021.8.26.1335, Culture=neutral, PublicKeyToken=null]].ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by MrMEEE** [comment]
I have tried compiling with dotnet 6.. same issue

**Comment by MrMEEE** [comment]
@stevesobol Who know anything about Linux clients?

**Comment by rcschaff82** [comment]
I believe I found a fix to this issue, but it still has issues.

edit /etc/gdm3/daemon.conf

add the following 2 lines under [daemon]
WaylandEnable=false
DefaultSession=gnome-xorg.desktop

That corrects that error, but there is still an error with .net6 and System.Drawing.Common.  Still working on a fix for this, but documentation points to adding this to the code:

System.Drawing.EnableUnixSupport set to true

**Comment by rcschaff82** [comment]
Ok. Fix for the second part:
modify the following files:
/usr/local/bin/Remotely/Remotely_Agent.runtimeconfig.json
/usr/local/bin/Remotely/Desktop/Remotely_Desktop.runtimeconfig.json

in both files change:
"configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
to:
"configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Drawing.EnableUnixSupport": true
    }


then restart the remotely -agent
