### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Lafarma** [immense/Remotely#467]
![image](https://user-images.githubusercontent.com/103105557/161931092-605155ea-9587-4811-9013-688668c956f5.png)
Hello.
Why this error happend?

**Comment by licenceit** [comment]
I have same problem. When i remove my db and let it to generate new its ok, but when i copy back my 120Mb database it wont start :/

**Comment by licenceit** [comment]
Log :
 at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Aug 17 10:54:37 remotely remotely[2852129]: fail: Microsoft.AspNetCore.Server.Kestrel[13]
Aug 17 10:54:37 remotely remotely[2852129]:       Connection id "0HMK05OENFF0C", Request id "0HMK05OENFF0C:00000002": An unhandled exception was thrown by the application.
Aug 17 10:54:37 remotely remotely[2852129]:       System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Aug 17 10:54:37 remotely remotely[2852129]:          at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer)
Aug 17 10:54:37 remotely remotely[2852129]:          at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
Aug 17 10:54:37 remotely remotely[2852129]:          at System.IO.StreamWriter.Write(String value)
Aug 17 10:54:37 remotely remotely[2852129]:          at Microsoft.AspNetCore.Hosting.Views.ErrorPage.ExecuteAsync()
Aug 17 10:54:37 remotely remotely[2852129]:          at Microsoft.Extensions.RazorViews.BaseView.ExecuteAsync(HttpContext context)
Aug 17 10:54:37 remotely remotely[2852129]:          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 ap
