### ISSUE TITLE
Linux Remotely Server Installer Build Actions fails

### ISSUE THREAD

**Issue by Basti-Fantasti** [immense/Remotely#502]
**Describe the bug**

Build using latest linux installer binary fails (**v2022.08.02.0428**)

**To Reproduce**
1. Forked immense/Remotely repo
2. enabled Actions
3. added new token for authentication
4. checked pinging the target url
5. downloaded latest linux "Remotely_Server_Installer" binary
6. called the installer with the following arguments from bash on my ubuntu host:

````bash

./Remotely_Server_Installer -b false -r latest -u Basti-Fantasti -p ghp_xxxxx -s https://my.remotely.install -i /var/www/remotely/ -w 1 -c true

````

and here's the output:

````
Performing server install.  GitHub User: Basti-Fantasti.  Server
URL: https://my.remotely.install/.  Installation Directory: /var/www/remotely/.
Web Server: UbuntuNginx.  Create New Build: True.  Git Reference:
v2022.08.02.0428

Get artifacts response status code: OK

Trigger GitHub Actions build.

Dispatch response status code: UnprocessableEntity

[PerformInstall] GitHub API call to trigger build action failed.
Do you have Actions enabled on your forked Remotely repo on
the Actions tab?  If not, enable them and try again. Otherwise,
please check your input parameters.

Installation completed.

````

**Remotely Version**
Linux Installer: v2022.08.02.0428

**Expected Behavior**
smoothly run the installation 😄 

**Screenshots**

enabled actions in my repo

![2022-08-02 21_46_42-Actions · Basti-Fantasti_Remotely](https://user-images.githubusercontent.com/1663072/182460437-0447b5f6-afb2-4b17-96ed-900522f0cc0e.png)

privileges of access token

![2022-08-02 21_49_29-Edit personal access token](https://user-images.githubusercontent.com/1663072/182460938-12589f15-9942-4903-a30a-e152f5b35b95.png)

**Comment by Basti-Fantasti** [comment]
I digged a little deeper and tried to manually run the build.yml action.

When doing so it cancels with an error as shown below:

Maybe there's a general issue with the latest build.yml file.

The build-mac event fails directly with the error below:

![2022-08-03 10_21_50-Build · Basti-Fantasti_Remotely@db11194](https://user-images.githubusercontent.com/1663072/182560346-3ba237eb-452e-4d25-b4ff-54a208ccfca7.png)

Maybe this causes the CLI tool to fail

**Comment by Basti-Fantasti** [comment]
yes it's related to the build.yml file.

I've increased the version of macos to 11 now the manual build process was successfully triggered and finished.
I'm currently running the installer binary with the "download existing artifacts" flag and for now it seems to run...

it successfully dowloaded the artifacts but runs ins an permission exception now:

````bash
Get artifacts response status code: OK

Downloading build artifact.

Download artifact response status code: OK

Extracting files.

Unhandled exception. System.UnauthorizedAccessException: Access to the path '/var/www/remotely/wwwroot/Identity/lib/bootstrap/LICENSE' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at Server.Installer.Services.ServerInstaller.PerformInstall(CliParams cliParams)
   at Server.Installer.Program.Main(String[] args)
   at Server.Installer.Program.<Main>(String[] args)

````

Installation is called as user root and all permissions are set to root:www-data - so should be ok

**Comment by Basti-Fantasti** [comment]
the last one was my fault. I've tried to make an installation instead of an update...

**Comment by JuniorGandara** [comment]
Same problem here, but the issue it's seems to be another one. 

![image](https://user-images.githubusercontent.com/22697027/192552820-120192bb-e853-4e48-aeb5-34fb2b3ba1ec.png)

**Comment by speedy01** [comment]
im stuck with the same output. but when I manually run build.yml, its completes without issue.

from cli
Dispatch response status code: UnprocessableEntity

[PerformInstall] GitHub API call to trigger build action failed.
Do you have Actions enabled on your forked Remotely repo on
the Actions tab?  If not, enable them and try again. Otherwise,
please check your input parameters.

Installation completed.

**Comment by john-clark** [comment]
Build and Test work fine for me but I have the same issue.  Using [v2022.09.16.1006 Release](https://github.com/immense/Remotely/releases/tag/v2022.09.16.1006) 
```
Performing server install.  GitHub User: gh-user.  Server
URL: https://full.website.url/.  Installation Directory: /var/www/remotely/.
Web Server: UbuntuNginx.  Create New Build: True.  Git Reference:
v2022.09.16.1006

Get artifacts response status code: OK

Trigger GitHub Actions build.

Dispatch response status code: UnprocessableEntity

[PerformInstall] GitHub API call to trigger build action failed.
Do you have Actions enabled on your forked Remotely repo on
the Actions tab?  If not, enable them and try again. Otherwise,
please check your input parameters.

Installation completed.
```

/var/www/remotely is empty
