### ISSUE TITLE
problem with .NET (starting application)

### ISSUE THREAD

**Issue by licenceit** [immense/Remotely#524]
Hello, 
we have problem with starting Remotely after update. When i check netstat I find out that server doesn't start listening on port 5000. After a lot of digging i find critical error (on the bottom of this text). To find this error I execute command: 
/usr/bin/dotnet /var/www/remotely/Remotely_Server.dll and it show this error right away. 

Thank you for help 

Dotnet is 6.0
OS: Ubuntu 20.04
remotely: v2022.09.16.1006

Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Remotely.Server.Startup.ConfigureServices(IServiceCollection services) in D:\a\1\s\Server\Startup.cs:line 49
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
         at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
         at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
         at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
         at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
         at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

EDIT:
Another error founded

Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "..................", Request id ".............:00000002": An unhandled exception was thrown by the application.
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
         at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer)
         at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
         at System.IO.StreamWriter.Write(String value)
         at Microsoft.Extensions.RazorViews.BaseView.EndWriteAttribute()
         at Microsoft.AspNetCore.Hosting.Views.ErrorPage.ExecuteAsync()
         at Microsoft.Extensions.RazorViews.BaseView.ExecuteAsync(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by licenceit** [comment]
OK so I found solution. Problem was in snapshots through the time, remotely database (SQLite) was in some .. interesting state.... I switch back to original instalation (one year old where it work). So now I have working remotely again with old database, BUT clients automaticaly connect to remotely because of server key and thats awesome. Only scripts missing, but I get them back from backups and digging in problematic database.
