### ISSUE TITLE
can't start Remotely on two computers.

### ISSUE THREAD

**Issue by jarx88** [immense/Remotely#553]
Hello,

I am having a problem with starting Remotely on two end computers. When I click on the desktop icon, nothing happens. In the admin panel, I see that these computers are online when I install the host on them, but the remote control does not start when I press the button.

![image](https://user-images.githubusercontent.com/31516391/210715382-b019942d-7c75-4110-a4f7-d14cd44fdf0d.png)

The client side log does not indicate much about what may be the cause.

In the server log, I have something like this:

Message:
[Error] [RequestPath:/ RequestId:0HMNE4RB7ROG0:00000002 - ConnectionId:0HMNE4RB7RODN - Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] | Message: An unhandled exception has occurred while executing the request. | Exception: Invalid URI: The hostname could not be parsed.

Stack Trace:
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions) at System.Uri..ctor(String uriString, UriKind uriKind) at Microsoft.AspNetCore.Components.NavigationManager.set_BaseUri(String value) at Microsoft.AspNetCore.Components.NavigationManager.Initialize(String baseUri, String uri) at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.Initialize(String baseUri, String uri) at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.<InitializeStandardComponentServicesAsync>g__InitializeCore|5_0(HttpContext httpContext) at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType) at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection) at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters) at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count) at Remotely.Server.Pages.Pages__Host.<>c__DisplayClass21_0.<<ExecuteAsync>b__1>d.MoveNext() in D:\a\1\s\Server\Pages\_Host.cshtml:line 59 --- End of stack trace from previous location --- at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync() at Remotely.Server.Pages.Pages__Host.ExecuteAsync() in D:\a\1\s\Server\Pages\_Host.cshtml:line 11 at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context) at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts) at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

In the client side log: (I removed the name of my domain from the links for security purposes.)
[Information]	2023-01-05 06:54:18.624	[Remotely.Agent.Services.AgentHubConnection]	Message: Attempting to connect to server.	
[Information]	2023-01-05 06:54:18.958	[Remotely.Agent.Services.AgentHubConnection]	Message: Connected to server.	
[Information]	2023-01-05 07:02:58.601	[HTTP HEAD https:///Content/Remotely-Win10-x64.zip - HTTP HEAD https:///Content/Remotely-Win10-x64.zip - System.Net.Http.HttpClient.Default.LogicalHandler]	Message: Start processing HTTP request HEAD https:///Content/Remotely-Win10-x64.zip	
[Information]	2023-01-05 07:02:58.609	[HTTP HEAD https:///Content/Remotely-Win10-x64.zip - HTTP HEAD https:///Content/Remotely-Win10-x64.zip - System.Net.Http.HttpClient.Default.ClientHandler]	Message: Sending HTTP request HEAD https:///Content/Remotely-Win10-x64.zip	
[Information]	2023-01-05 07:02:58.833	[HTTP HEAD https:///Content/Remotely-Win10-x64.zip - HTTP HEAD https:///Content/Remotely-Win10-x64.zip - System.Net.Http.HttpClient.Default.ClientHandler]	Message: Received HTTP response headers after 220.972ms - 304	
[Information]	2023-01-05 07:02:58.834	[HTTP HEAD https://Content/Remotely-Win10-x64.zip - HTTP HEAD https:///Content/Remotely-Win10-x64.zip - System.Net.Http.HttpClient.Default.LogicalHandler]	Message: End processing HTTP request after 256.6635ms - 304	
[Information]	2023-01-05 07:02:58.992	[Remotely.Agent.Services.AgentHubConnection]	Message: Attempting to connect to server.	
[Information]	2023-01-05 07:02:59.360	[Remotely.Agent.Services.AgentHubConnection]	Message: Connected to server.	

What I tried to do:

Install ASP.NET Core 3.1 Runtime (v3.1.32) on the client
Enable .NET Framework functions from the control panel
Unlock port 5000 in the Windows firewall

Unfortunately, this did not work. What else can I do?

The computers have Windows 10 version 22H2 19045.2364.

**Comment by rockenrooster** [comment]
I am having the exact same problem. Before docker I use to be able to remote connect to the computers in my list, but now I can't.
Maybe it has to do with the removal of WebRTC???

**Comment by lucent-sea** [comment]
Other, another step. 

- Try manually running `C:\Program Files\Remotely\Desktop\Remotely_Desktop.exe`.
  - You should see it prompt for server URL, because this one doesn't have it embedded and relies on the agent to pass it in via command line args.
  - If it doesn't launch, does the process exist in Task Manager?  Is there an error in Event Viewer?

**Comment by rockenrooster** [comment]
Using docker image from 1/4/2023
Redirect to HTTPS is enabled
The Host property in C:\Program Files\Remotely\ConnectionInfo.json on the client computer is indeed using HTTPS
I've tried launching Remotely_Desktop.exe but it crashes after 1 sec (Appears in Task Manager and goes away)
When I run that exe, 43 events are generated in event viewer, 2 Errors and the rest Informational.

1 Event ID 1026 (.NET Runtime):

Application: Remotely_Desktop.exe
CoreCLR Version: 6.0.1222.56807
.NET Version: 6.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at NAudio.Wave.WasapiLoopbackCapture.GetDefaultLoopbackCaptureDevice()
   at NAudio.Wave.WasapiLoopbackCapture..ctor()
   at Immense.RemoteControl.Desktop.Windows.Services.AudioCapturerWin..ctor() in D:\a\1\s\submodules\Immense.RemoteControl\Desktop.Windows\Services\AudioCapturerWin.cs:line 16
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Immense.RemoteControl.Desktop.Shared.Extensions.IServiceCollectionExtensions.BuildRemoteControlServiceProvider(IServiceCollection services, String[] args, Action`1 clientConfig, Action`1 platformServicesConfig, Func`2 startupConfig, String serverUri) in D:\a\1\s\submodules\Immense.RemoteControl\Desktop.Shared\Extensions\IServiceCollectionExtensions.cs:line 170
   at Immense.RemoteControl.Desktop.Windows.Startup.UseRemoteControlClient(String[] args, Action`1 clientConfig, Action`1 serviceConfig, Func`2 startupConfig, String serverUri) in D:\a\1\s\submodules\Immense.RemoteControl\Desktop.Windows\Startup.cs:line 45
   at Program.<Main>$(String[] args) in D:\a\1\s\Desktop.Win\Program.cs:line 27
   at Program.<Main>(String[] args)

2nd Error is Event ID 1000 (Application Error):

Faulting application name: Remotely_Desktop.exe, version: 2023.1.4.634, time stamp: 0x6377dc84
Faulting module name: KERNELBASE.dll, version: 10.0.20348.1366, time stamp: 0xa5747ac1
Exception code: 0xe0434352
Fault offset: 0x000000000003ef5c
Faulting process id: 0x80
Faulting application start time: 0x01d922040ad37dac
Faulting application path: C:\Program Files\Remotely\Desktop\Remotely_Desktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c8d7d56c-6e7f-4aaa-9015-e5fe347b17e8
Faulting package full name: 
Faulting package-relative application ID:

**Comment by rockenrooster** [comment]
Also note that I have been using Caddy as a reverse proxy for Remotely since early last year with this config (fake domain): 
remote.fakedomain.fakedomain.com {
        reverse_proxy 192.168.1.23:5000
}

**Comment by lucent-sea** [comment]
I see what's going on.  The audio capture library (NAudio) is throwing an exception.  I probably can't do anything about that, but I can make it so it doesn't crash Remotely.  It should have been that way from the start.  Oversight on my part.

I'll have this fixed in the next release (probably today or tomorrow).

**Comment by rockenrooster** [comment]
Ok interesting, because the computer in question is a VM and I don't think it has any sound device. Let me add one and see if that fixes my issue at least until you fix it so it doesn't crash in the next release

**Comment by rockenrooster** [comment]
Update: Adding a sound device to the VM fixed the problem. Looking forward to the next release!

**Comment by lucent-sea** [comment]
Thanks for confirming that!

I've published a new release to both Docker and GitHub.  Release notes are here:  https://github.com/immense/Remotely/releases/tag/v2023.01.06.1648

Let me know if this solves the problem!

**Comment by jarx88** [comment]
Hello. It's working now :) 
The installer sets the default connection type to `http` by default. I had to set it in the Nginx Proxy Manager settings and now everything is working. 
![image](https://user-images.githubusercontent.com/31516391/211144238-bc294e56-c556-4bbe-96f6-ded35c0e3045.png)

and

![image](https://user-images.githubusercontent.com/31516391/211144259-cc2b2250-2992-4886-9a4a-0cb85a8bf078.png)

Additionally, in the panel.

![image](https://user-images.githubusercontent.com/31516391/211144275-732af1ca-b65a-4501-91c2-bbe79232ce65.png)

Otherwise, the computer wouldn't show up on the list. I suspect this is because the installer downloaded from the panel has `http` set as the default. The panel is handled through `Https`.

**Comment by lucent-sea** [comment]
@jarx88  Thanks for the update!

With the latest image, the scheme should be set automatically to whatever was used to download the file.  If it's not, then some headers aren't being set correctly, or the proxy isn't trusted.

For example, Nginx config would use:  `proxy_set_header   X-Forwarded-Proto $scheme;`  This will forward the request scheme to the dotnet service.

If the reverse proxy IP is a loopback address (e.g. 127.0.0.1) or Docker default host (172.17.0.1), Remotely will use whatever's in this header as the request scheme.  If it's not one of those IP addresses, you'll need to add the reverse proxy IP to `KnownProxies` in `appsettings.json`.

A full example config is in the readme here:  https://hub.docker.com/r/immybot/remotely

If what you have is working for you, then great.  Just figured I'd provide the above info in case it's helpful.

Personally, I use Caddy, since it defaults to all the correct settings, and it acquires an SSL cert automatically.  The config is just 3 lines.

I'll close this one out for now.
