### ISSUE TITLE
Sessions fail to start

### ISSUE THREAD

**Issue by blaine07** [immense/Remotely#629]
Self-hosting Remotely on Unraid with Docker.

When I hit "remote control" it always "fails to start session." It did work at one point; not positive if it quit working around when it recently upgraded or not. Tried to roll back to a older version of container but still couldn't get it to connect to any devices either.

In error log, I cleared it and cant get it to put anything in error log. 

I can't remotely access anything. 

What are the next steps I can do to help gather more information to rectify and be able to use remotely again?

**Comment by blaine07** [comment]
`Entered main script.
Starting Remotely server.
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {28385229-330c-4f60-8d03-8f22d1d3a42b} may be persisted to storage in unencrypted form.
Entered main script.
Starting Remotely server.
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
       ---> System.Security.Cryptography.CryptographicException: The key {382c0bee-675b-4a0d-b954-a41bd7b051c9} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
warn: Immense.RemoteControl.Server.Services.DesktopHubSessionCache[0]
      Removing expired session: {"AccessKey":"","AgentConnectionId":"khPfNGoY-1FJzsegaQbwxw","AttendedSessionId":"","Created":"2023-05-10T20:52:55.5341068+00:00","DesktopConnectionId":"","MachineName":"","Mode":0,"NotifyUserOnStart":false,"OrganizationName":"","RelativeAccessUri":"/RemoteControl/Viewer?mode=Unattended\u0026sessionId=86c5769c-df77-445b-88e6-db68b3c16f51\u0026accessKey=\u0026viewonly=False","RequesterName":"","RequesterUserName":"","RequireConsent":false,"StartTime":"0001-01-01T00:00:00+00:00","StreamId":"00000000-0000-0000-0000-000000000000","UnattendedSessionId":"86c5769c-df77-445b-88e6-db68b3c16f51","UserConnectionId":"911c1954-f4ee-45e9-a757-452f0c6b875c","ViewerList":[],"ViewOnly":false}
warn: Immense.RemoteControl.Server.Services.DesktopHubSessionCache[0]
      Removing expired session: {"AccessKey":"","AgentConnectionId":"B8uyNzfs-D2g78BKDNE_Zw","AttendedSessionId":"","Created":"2023-05-10T21:01:12.7647398+00:00","DesktopConnectionId":"","MachineName":"","Mode":0,"NotifyUserOnStart":false,"OrganizationName":"","RelativeAccessUri":"/RemoteControl/Viewer?mode=Unattended\u0026sessionId=7df1d2e6-4454-4b3a-bd7a-12b6c6212b35\u0026accessKey=\u0026viewonly=False","RequesterName":"","RequesterUserName":"","RequireConsent":false,"StartTime":"0001-01-01T00:00:00+00:00","StreamId":"00000000-0000-0000-0000-000000000000","UnattendedSessionId":"7df1d2e6-4454-4b3a-bd7a-12b6c6212b35","UserConnectionId":"75998bb2-cf2b-4f8a-99e4-2936f6258845","ViewerList":[],"ViewOnly":false}
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
       ---> System.Security.Cryptography.CryptographicException: The key {382c0bee-675b-4a0d-b954-a41bd7b051c9} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
Entered main script.
Starting Remotely server.
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Entered main script.
Starting Remotely server.
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Entered main script.
Starting Remotely server.
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
Entered main script.
Starting Remotely server.
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
       ---> System.Security.Cryptography.CryptographicException: The key {fd7736c5-3d74-4e42-881b-5299def7d032} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
warn: Immense.RemoteControl.Server.Services.DesktopHubSessionCache[0]
      Removing expired session: {"AccessKey":"","AgentConnectionId":"omcqdr-ewQAlcy8R8bbapA","AttendedSessionId":"","Created":"2023-05-10T21:34:59.8385702+00:00","DesktopConnectionId":"","MachineName":"","Mode":0,"NotifyUserOnStart":false,"OrganizationName":"","RelativeAccessUri":"/RemoteControl/Viewer?mode=Unattended\u0026sessionId=28996bc8-c6a2-4925-83f3-7eee4ee3513f\u0026accessKey=\u0026viewonly=False","RequesterName":"","RequesterUserName":"","RequireConsent":false,"StartTime":"0001-01-01T00:00:00+00:00","StreamId":"00000000-0000-0000-0000-000000000000","UnattendedSessionId":"28996bc8-c6a2-4925-83f3-7eee4ee3513f","UserConnectionId":"21f619c0-1d66-4f18-abb4-0e143ca3782b","ViewerList":[],"ViewOnly":false}`

Does this suggest anything helpful?

**Comment by lucent-sea** [comment]
Unfortunately, no, there's nothing unusual there.

The warnings are normal.  Data protection and antiforgery keys aren't persisted to durable storage and get wiped when the container restarts.  Afterward, when your browser tries to use them from the stored cookie, it fails on the server.  That's why "remember me" doesn't persist through container restarts.

You'll want to look in the logs on the remote machine, within `C:\ProgramData\Remotely\Logs`.  It could be in either the agent or desktop logs, depending on where the issue is happening.

**Comment by blaine07** [comment]
> Unfortunately, no, there's nothing unusual there.
> 
> The warnings are normal. Data protection and antiforgery keys aren't persisted to durable storage and get wiped when the container restarts. Afterward, when your browser tries to use them from the stored cookie, it fails on the server. That's why "remember me" doesn't persist through container restarts.
> 
> You'll want to look in the logs on the remote machine, within `C:\ProgramData\Remotely\Logs`. It could be in either the agent or desktop logs, depending on where the issue is happening.

We’ll, unsure what REAL issue was but I turned OFF/DISABLED: 

-Forced Client HTTPS
-Redirect to HTTPS
-Use HSTS

and now everything is working. 

Appears still getting HTTPS though so not sure any of that is important in long run? Sending it through a cloudflare tunnel into a Nginx Proxy Manager to Unraid Server. 

Should I consider turning any of the above things back on??

**Comment by lucent-sea** [comment]
It's recommended that you keep HSTS on.  You can read more about it [here](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-7.0&tabs=visual-studio%2Clinux-ubuntu#http-strict-transport-security-protocol-hsts).  I think that should only affect browser clients, though, not the .NET agent.

Redirect to HTTPS is only useful if the dotnet server process is receiving web requests directly via HTTPS, and you want all HTTP traffic redirected.  In most cases, people have a reverse proxy in front of it that handles HTTPS.  This might be the culprit.

I added Force Client HTTPS for situations where the X-Forwarded-Proto header wasn't getting forwarded correctly from reverse proxies or firewalls, and the client tries to (unsuccessfully) connect via HTTP.  So if it's working without it, and the client is using HTTPS, then you don't need it.

**Comment by blaine07** [comment]
> It's recommended that you keep HSTS on. You can read more about it [here](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-7.0&tabs=visual-studio%2Clinux-ubuntu#http-strict-transport-security-protocol-hsts). I think that should only affect browser clients, though, not the .NET agent.
> 
> Redirect to HTTPS is only useful if the dotnet server process is receiving web requests directly via HTTPS, and you want all HTTP traffic redirected. In most cases, people have a reverse proxy in front of it that handles HTTPS. This might be the culprit.
> 
> I added Force Client HTTPS for situations where the X-Forwarded-Proto header wasn't getting forwarded correctly from reverse proxies or firewalls, and the client tries to (unsuccessfully) connect via HTTP. So if it's working without it, and the client is using HTTPS, then you don't need it.

I will turn HSTS back on and give it a bit to settle down. Yeah, I bet you’re right, I probably don’t need Redirect to HTTPS or Force Client HTTPS too. I have cloudflare forcing HTTPS too so it should only be hitting NPM as HTTPS too; I assume it would respect the X-Forwarded-Proto headers. 

Thank you!!! I appreciate your help; you’ve got something great coming with this. Ended up here playing around with the unfortunate uncertainty of MeshCentral; this is shaping up to be a solid actively developed alternative — THANK YOU!

**Comment by blaine07** [comment]
![IMG_3444](https://github.com/immense/Remotely/assets/63940698/ec8aae26-9dfc-47eb-9a16-ad9aeee71cbd)

I should leave HSTS enabled here, too?

**Comment by lucent-sea** [comment]
Sorry, I forgot to reply here.  Yeah, if it's working with HSTS enabled, I'd leave it on.
