### ISSUE TITLE
UNIQUE constraint failed: BrandingInfos.Id

### ISSUE THREAD

**Issue by Dominion0815** [immense/Remotely#674]
I get this error message if I try to click on "Branding" (new remotely user account):

```
remotely-remotely-1  | [10:44:53 WRN] Unhandled exception rendering component: An error occurred while saving the entity changes. See the inner exception for details. {EventId={Id=100, Name="ExceptionRenderingComponent"}, SourceContext="Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer", TransportConnectionId="zF8OwUwFgQqfSBoL9TFzbw", RequestId="0HMROHJTC19DK:00000001", RequestPath="/_blazor", ConnectionId="0HMROHJTC19DK", ThreadId=27}
remotely-remotely-1  | Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
remotely-remotely-1  |  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: BrandingInfos.Id'.
remotely-remotely-1  |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
remotely-remotely-1  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
remotely-remotely-1  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
remotely-remotely-1  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
remotely-remotely-1  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
remotely-remotely-1  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
remotely-remotely-1  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
remotely-remotely-1  |    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
remotely-remotely-1  |    --- End of inner exception stack trace ---
```

**To Reproduce**
1. Upgrade from old Remotely Version to new

**Remotely Version**
Version: 2023.06.19.0759

**Additional Context**

- I am running Remotely in Docker

**Comment by Dominion0815** [comment]
seems to be fixed
