### ISSUE TITLE
redirection issue?

### ISSUE THREAD

**Issue by shlv3r** [immense/Remotely#872]
hello 
i am on Windows desktop with docker remotely is install properly, it work on my pc where he is install (192.168.1.66:5371) no problem
but i dont understand why on my 2nd desktop PC  (192.168.1.55) witch is on the same LAN, i can't open in my browser remotely with server ip.
I think it s just a redirection but what i have missed?
port 80 and 443 tcp are onpen on my box on 192.168.1.66
thx for your help

error message from my  french browser : 
Ce site est inaccessible192.168.1.66 a mis trop de temps à répondre.
Voici quelques conseils :
Vérifier la connexion
[Vérifier le proxy et le pare-feu](chrome-error://chromewebdata/#buttons)
[Exécutez les diagnostics réseau de Windows](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT

server remotly log : 
2024-04-10 11:05:15.169 +00:00 [WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning { EventId: { Id: 60, Name: "UsingEphemeralFileSystemLocationInContainer" }, SourceContext: "Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository", ThreadId: 1 }
2024-04-10 11:05:19.704 +00:00 [WRN] No XML encryptor configured. Key {05d260b3-f557-4dc7-bdd6-91aa35ec2f24} may be persisted to storage in unencrypted form. { EventId: { Id: 35, Name: "NoXMLEncryptorConfiguredKeyMayBePersistedToStorageInUnencryptedForm" }, SourceContext: "Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager", ThreadId: 1 }
2024-04-10 11:05:43.494 +00:00 [WRN] Failed to determine the https port for redirect. { EventId: { Id: 3, Name: "FailedToDeterminePort" }, SourceContext: "Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware", RequestId: "0HN2P9OL4L235:00000001", RequestPath: "/", ConnectionId: "0HN2P9OL4L235", ThreadId: 16 }
2024-04-10 11:07:08.840 +00:00 [INF] User created a new account with password. { SourceContext: "Remotely.Server.Components.Account.Pages.Register", RequestId: "0HN2P9OL4L23G:00000001", RequestPath: "/Account/Register", ConnectionId: "0HN2P9OL4L23G", ThreadId: 21 }
2024-04-10 11:07:09.158 +00:00 [ERR] Error while sending email. { SourceContext: "Remotely.Server.Services.EmailSenderEx", RequestId: "0HN2P9OL4L23G:00000001", RequestPath: "/Account/Register", ConnectionId: "0HN2P9OL4L23G", ThreadId: 21 }
MimeKit.ParseException: No address found.
   at MimeKit.InternetAddress.TryParse(AddressParserFlags flags, ParserOptions options, Byte[] text, Int32& index, Int32 endIndex, Int32 groupDepth, InternetAddress& address)
   at MimeKit.MailboxAddress.TryParse(ParserOptions options, Byte[] text, Int32& index, Int32 endIndex, Boolean throwOnError, MailboxAddress& mailbox)
   at MimeKit.MailboxAddress.Parse(ParserOptions options, String text)
   at MimeKit.MailboxAddress.Parse(String text)
   at Remotely.Server.Services.EmailSenderEx.SendEmailAsync(String toEmail, String replyTo, String subject, String htmlMessage, String organizationID) in D:\a\1\s\Server\Services\EmailSender.cs:line 69

**Comment by shlv3r** [comment]
its all good i change the docker compose config with another port
