### ISSUE TITLE
Opening interface in Firefox locks up

### ISSUE THREAD

**Issue by FinlayDaG33k** [immense/Remotely#942]
**Describe the bug**
Open the web interface, login and immediately, all UI components "lock up".
Clicking any of the menu items yields nothing.  

**To Reproduce**

1. Login using Firefox.
2. Error appears.

**Remotely Version**
Server (can be found on about page): 2024.08.07.0819
Agent (can be found in device card): 2024.08.07.0819

**Expected Behavior**
No errors and the UI to not "lock up"

**Screenshots**

![image](https://github.com/user-attachments/assets/f1dfccf1-714a-4289-ae7a-5d8b14e1807d)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox 128.0.3

**Additional Context**

Log gives me the following stacktrace:
```
[21:29:17 WRN] Unhandled exception rendering component: TypeError: n.parentNode is null {EventId={Id=100, Name="ExceptionRenderingComponent"}, SourceContext="Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer", TransportConnectionId="p7RYzHiNAnVv3PCPcuCFuQ", RequestId="0HN6V7BRA9UO4:00000001", RequestPath="/_blazor", ConnectionId="0HN6V7BRA9UO4", ThreadId=20}

System.InvalidOperationException: TypeError: n.parentNode is null

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)

[21:29:17 ERR] Unhandled exception in circuit 'ZWMzCfnXs8KlwRzANHA3qvaRSGKtLgZLoQtzjWrv3kg'. {EventId={Id=111, Name="CircuitUnhandledException"}, SourceContext="Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost", TransportConnectionId="p7RYzHiNAnVv3PCPcuCFuQ", RequestId="0HN6V7BRA9UO4:00000001", RequestPath="/_blazor", ConnectionId="0HN6V7BRA9UO4", ThreadId=20}

System.AggregateException: One or more errors occurred. (TypeError: n.parentNode is null)

 ---> System.InvalidOperationException: TypeError: n.parentNode is null

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)

   --- End of inner exception stack trace ---
```

Everything works fine when using Edge.  
Devices do appear and disappear very often as well, so I don't know if this is related.

Using the following config for Nginx:
```
server {
    listen        80 default_server;
    server_name   localhost remotely.finlaydag33k.nl;
    location / {
        proxy_pass         http://remotely:8080;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
    location /_blazor {    
        proxy_pass http://remotely:8080;    
        proxy_http_version 1.1;    
        proxy_set_header Upgrade $http_upgrade;    
        proxy_set_header Connection "upgrade";    
        proxy_set_header Host $host;    
        proxy_cache_bypass $http_upgrade;    
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;    
        proxy_set_header   X-Forwarded-Proto $scheme;    
    }    
    location /AgentHub {    
        proxy_pass http://remotely:8080;    
        proxy_http_version 1.1;    
        proxy_set_header Upgrade $http_upgrade;    
        proxy_set_header Connection "upgrade";    
        proxy_set_header Host $host;    
        proxy_cache_bypass $http_upgrade;    
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;    
        proxy_set_header   X-Forwarded-Proto $scheme;    
    }    
    location /ViewerHub {    
        proxy_pass http://remotely:8080;    
        proxy_http_version 1.1;    
        proxy_set_header Upgrade $http_upgrade;    
        proxy_set_header Connection "upgrade";    
        proxy_set_header Host $host;    
        proxy_cache_bypass $http_upgrade;    
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;    
        proxy_set_header   X-Forwarded-Proto $scheme;    
    }    
    location /CasterHub {    
        proxy_pass http://remotely:8080;    
        proxy_http_version 1.1;    
        proxy_set_header Upgrade $http_upgrade;    
        proxy_set_header Connection "upgrade";    
        proxy_set_header Host $host;    
        proxy_cache_bypass $http_upgrade;    
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;    
        proxy_set_header   X-Forwarded-Proto $scheme;    
    }
}
```

**Comment by uwzis** [comment]
I have the same thing here. It also happens on all other web browsers and magically goes away at random...
